apiVersion: v1
kind: Secret
metadata: 
  name: chatapp-secrets
  namespace: chat-app 
type: Opaque
data:
  jwt: OWQ3MjliODFkNjM3Mjg2MjljMTE2OGE1OGMxMmYxMzljYTA5ODZiNTZmZGU2N2NiNjZhYjFiZDRmZjc3YTY3YQ== 